version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024MB"

  logstash:
    image: logstash:8.12.0
    volumes:
      - ./internal/adaptor/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./internal/adaptor/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    ports:
#      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
#      - "9600:9600"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024MB"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.17
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024MB"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: on-failure
    environment:
      - LOG_LEVEL=DEBUG
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=4318
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024MB"
    depends_on:
      - elasticsearch